# Generated by Django 4.1.7 on 2023-02-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
